### ISSUE TITLE
How to make it support OSX platform with cocoapods?

### ISSUE THREAD

**Issue by qichunren** [chebur/pjsip#5]
I wish it not only support iOS, but also OSX. Thanks.

https://github.com/CocoaPods/Specs/blob/master/pjsip/2.2/pjsip.podspec

**Comment by welljsjs** [comment]
I don't think it's impossible (although something might have changed since 2014, so just take my comment as a suggestion). 
As [OpenSSL-Universal](https://github.com/krzyzanowskim/OpenSSL) does, it seems to be pretty easy. We need separate builds, but that does not seem to be a problem anymore. I'll dive a little deeper into this topic, give me some time and I'll come back.
