### ISSUE TITLE
When made a Outgoing VOIP Call and disconnect without receiving at the destinatoin side, it does not disconnect properly.

### ISSUE THREAD

**Issue by parthbarot10** [chebur/pjsip#98]
```
11:31:51.843           pjsua_call.c  Hangup all calls..
11:31:51.843           pjsua_call.c  .Call 0 hanging up: code=0..
11:31:51.844      sip_transaction.c  ....Unable to register CANCEL transaction (key exists)
11:31:51.844           pjsua_call.c  ..Failed to send end session message: Object already exists (PJ_EEXISTS) [status=70015]

**Comment by welljsjs** [comment]
Hi, thanks for filing a report, are you sure you're reporting to the correct repository?

See the issue template:
>  I'm reporting the issue to the correct repository as it is related to this repository and not to the [official pjsip repository](https://www.pjsip.org)

**Comment by parthbarot10** [comment]
Okay, thank you very much. Please update if you fix this issue.

**Comment by welljsjs** [comment]
> Okay, thank you very much. Please update if you fix this issue.

Sorry I think you misunderstood; I don't think the issue you filed is related to this repository but instead to the official pjpsip repository: https://www.pjsip.org/

**Comment by parthbarot10** [comment]
But I installed this repository pod and used it in my project. and facing this issue.
pod 'pjsip'

**Comment by welljsjs** [comment]
Yeah true but we're not the developers of pjsip and thus are not responsible for anything to do with the internals of pjsip.

The only purpose of this repository is to make pjsip available for iOS/macOS, i.e. building & compiling pjsip for iOS which you would otherwise have to do manually (that would mean having to download the pjsip source files, configure & build manually). 

You'll want to reach out to us only if there's an issue specific to the build process, e.g. when compiling your project in Xcode or similar.

Hope this made things a little clearer.

As to where to report bugs for the official pjsip sources, I think you can subscribe to their mailing lists and post a comment there. 

Let me know if you have any further questions.

**Comment by parthbarot10** [comment]
Okay, thanks for the help.
